import React, { useEffect, useState } from "react";
import { reportsAPI } from "../services/api";
import Spinner from "../components/Spinner";

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [format, setFormat] = useState("pdf");

  const loadReports = () => {
    setLoading(true);
    reportsAPI
      .list()
      .then(({ data }) => setReports(data.results || data))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadReports();
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      await reportsAPI.generate({ title: "Demand Forecast Report", report_format: format, filters: {} });
      loadReports();
    } finally {
      setGenerating(false);
    }
  };

  if (loading) return <Spinner size="lg" label="Loading reports..." />;

  return (
    <div className="page">
      <div className="page__header page__header--with-action">
        <div>
          <h1>Reports</h1>
          <p>PDF and Excel exports of sales, forecasts, and recommendations.</p>
        </div>
        <div className="page__header-actions">
          <select value={format} onChange={(e) => setFormat(e.target.value)} className="select">
            <option value="pdf">PDF</option>
            <option value="excel">Excel</option>
          </select>
          <button className="btn btn--primary" onClick={handleGenerate} disabled={generating}>
            <i className="bi bi-file-earmark-plus" /> {generating ? "Generating..." : "Generate report"}
          </button>
        </div>
      </div>

      <section className="panel">
        <table className="data-table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Format</th>
              <th>Generated By</th>
              <th>Created</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((r) => (
              <tr key={r.id}>
                <td>{r.title}</td>
                <td>{r.report_format.toUpperCase()}</td>
                <td>{r.generated_by_name}</td>
                <td>{new Date(r.created_at).toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </div>
  );
}